# Generated by Django 4.0.3 on 2022-03-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CRAWAL_TIME',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('tweet_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('screenName', models.CharField(blank=True, db_column='screenName', max_length=100, null=True)),
                ('tweetData', models.CharField(blank=True, db_column='tweetData', max_length=100, null=True)),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('sentiment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'SENTIMENT',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('negativeAnl', models.CharField(blank=True, db_column='negativeAnl', max_length=100, null=True)),
                ('positiveAnl', models.CharField(blank=True, db_column='positiveAnl', max_length=100, null=True)),
                ('neutralAnl', models.CharField(blank=True, db_column='neutralAnl', max_length=100, null=True)),
            ],
            options={
                'db_table': 'SENTIMENT_ANALYSIS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TopHashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(blank=True, max_length=100, null=True)),
                ('countTotal', models.IntegerField(blank=True, db_column='countTotal', null=True)),
            ],
            options={
                'db_table': 'TOP_HASHTAG',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TopKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(blank=True, max_length=100, null=True)),
                ('countTotal', models.IntegerField(blank=True, db_column='countTotal', null=True)),
            ],
            options={
                'db_table': 'TOP_KEYWORD',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TopLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(blank=True, max_length=100, null=True)),
                ('countTotal', models.IntegerField(blank=True, db_column='countTotal', null=True)),
            ],
            options={
                'db_table': 'TOP_LINK',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TopMentions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention', models.CharField(blank=True, max_length=100, null=True)),
                ('countTotal', models.IntegerField(blank=True, db_column='countTotal', null=True)),
            ],
            options={
                'db_table': 'TOP_MENTIONS',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TopUser',
            fields=[
                ('userid', models.AutoField(db_column='userID', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='userName', max_length=100)),
                ('likeCount', models.IntegerField(blank=True, db_column='likeCount', null=True)),
                ('sentiment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'TOP_USER',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TweetType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweetCount', models.IntegerField(blank=True, db_column='tweetCount', null=True)),
                ('recount', models.IntegerField(blank=True, db_column='reCount', null=True)),
            ],
            options={
                'db_table': 'TWEET_TYPE',
                'managed': True,
            },
        ),
    ]
