# Generated by Django 4.0.3 on 2022-03-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newAPI', '0002_delete_crawltime_sentiment_likes_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawl_Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CRAWL_TIME',
                'managed': True,
            },
        ),
    ]
