# Generated by Django 4.0.3 on 2022-03-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newAPI', '0003_crawl_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Crawl_Time',
            new_name='CrawlTime',
        ),
    ]
