# Generated by Django 4.0.3 on 2022-03-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newAPI', '0004_rename_crawl_time_crawltime'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='crawltime',
            table='CRAWAL_TIME',
        ),
    ]
