# Generated by Django 4.0.3 on 2022-03-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newAPI', '0005_alter_crawltime_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentiment',
            name='link',
            field=models.CharField(blank=True, db_column='link', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='pre_tweetData',
            field=models.CharField(blank=True, db_column='pre_tweetData', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='profile_image_url_https',
            field=models.CharField(blank=True, db_column='profile_image_url_https', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sentiment',
            name='retweet_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='screenName',
            field=models.CharField(blank=True, db_column='screenName', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='sentiment',
            name='tweetData',
            field=models.CharField(blank=True, db_column='tweetData', max_length=1000, null=True),
        ),
    ]
