# Generated by Django 3.2.9 on 2022-07-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newAPI', '0006_sentiment_link_sentiment_pre_tweetdata_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CrawlTime',
        ),
        migrations.DeleteModel(
            name='Sentiment',
        ),
        migrations.DeleteModel(
            name='SentimentAnalysis',
        ),
        migrations.DeleteModel(
            name='TopHashtag',
        ),
        migrations.DeleteModel(
            name='TopKeyword',
        ),
        migrations.DeleteModel(
            name='TopLink',
        ),
        migrations.DeleteModel(
            name='TopMentions',
        ),
        migrations.DeleteModel(
            name='TopUser',
        ),
        migrations.DeleteModel(
            name='TweetType',
        ),
    ]
